// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5fuxRUzVFbNm20v1VJN_r83kFn9OOkc',
    appId: '1:647906777944:web:d71cf402b6aff5f430e32d',
    messagingSenderId: '647906777944',
    projectId: 'act-17-643f3',
    authDomain: 'act-17-643f3.firebaseapp.com',
    storageBucket: 'act-17-643f3.firebasestorage.app',
    measurementId: 'G-ZMHR8NMX6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ds_KDW1qejkpyz-SiSq_Xz3rJaF8drU',
    appId: '1:647906777944:android:10420f0c9e679b6430e32d',
    messagingSenderId: '647906777944',
    projectId: 'act-17-643f3',
    storageBucket: 'act-17-643f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ6tH0fbiXTd7Ws2hTctZQfWSlCsBzCCk',
    appId: '1:647906777944:ios:cd70b1156297c29930e32d',
    messagingSenderId: '647906777944',
    projectId: 'act-17-643f3',
    storageBucket: 'act-17-643f3.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ6tH0fbiXTd7Ws2hTctZQfWSlCsBzCCk',
    appId: '1:647906777944:ios:cd70b1156297c29930e32d',
    messagingSenderId: '647906777944',
    projectId: 'act-17-643f3',
    storageBucket: 'act-17-643f3.firebasestorage.app',
    iosBundleId: 'com.example.act17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr5fuxRUzVFbNm20v1VJN_r83kFn9OOkc',
    appId: '1:647906777944:web:1a2cda3e8beb741e30e32d',
    messagingSenderId: '647906777944',
    projectId: 'act-17-643f3',
    authDomain: 'act-17-643f3.firebaseapp.com',
    storageBucket: 'act-17-643f3.firebasestorage.app',
    measurementId: 'G-7YF1Z8SY90',
  );

}